spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.43.10.96:3306/ROSIEDEV
    username: ROSIE
    password: rosie1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
logging.level:
  org.hibernate.SQL: debug
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
file:
  dir: C:/Users/thd65/java/commnuity/src/main/resources/static/upload-files/


# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate

